import Header from './component/Header'
import Footer from './component/Footer'

import './globals.css'
import './page.module.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hasan Next  App',
  description: 'Generated by create next app. Developed by hasan',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Header/>
        {children}
       <Footer/>
        </body>
    </html>
  )
}
